version: '3.9'

services:
  database: 
    image: bitnami/postgresql
    container_name: database
    ports: 
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=admin
      - POSTGRESQL_PASSWORD=go1063528travel
      - POSTGRESQL_DATABASE=gotravel
    volumes:
      - pgdata:/bitnami/postgresql

  server:
    build: .
    container_name: api
    restart: always
    volumes:
      - .:/usr/app
      - /usr/app/node_modules
    ports:
      - 3333:3333
    links: 
      - database
    depends_on:
      - database

volumes:
  pgdata:
    driver: local
